<a href="https://colab.research.google.com/github/mikeogunmakin/research/blob/main/machine%20learning/data_gathering/importing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Reading Data Into Python**

In [1]:
import pandas as pd

### **Reading in CSV files**

In [22]:
## Reading CSV files

df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [21]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

[Read More for Documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) on `pd.read_csv`

### **Reading in Excel files**

In [23]:
## Reading Excel files

df = pd.read_excel('/content/drive/MyDrive/stock portfolio performance data set.xlsx',sheet_name=4, header =1)
## header set to 1 to use the second row as the header

In [24]:
df.head()

,ID,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.139,0.010,1.33,0.149,0.663,0.525,0.531875,0.478116,0.738015,0.800000,0.52,0.411765
1,2,0.0,1.0,0.0,0.0,0.0,0.0,0.143,0.010,1.17,0.108,0.663,0.650,0.549712,0.487595,0.571579,0.412231,0.52,0.764706
2,3,0.0,0.0,1.0,0.0,0.0,0.0,0.173,0.018,1.30,0.144,0.638,0.513,0.692625,0.629895,0.703051,0.756879,0.44,0.376471
3,4,0.0,0.0,0.0,1.0,0.0,0.0,0.096,-0.002,1.39,0.144,0.613,0.475,0.324351,0.255634,0.800000,0.756046,0.36,0.270588
4,5,0.0,0.0,0.0,0.0,1.0,0.0,0.096,0.001,1.04,0.087,0.725,0.538,0.326615,0.306501,0.432452,0.209289,0.72,0.447059

[Read More for Documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) on `pd.read_excel`

### **Reading in JSON files**

In [18]:
df = pd.read_json('/content/sample_data/anscombe.json')

In [19]:
df.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

[Read More for Documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html) on `pd.read_json`

For other file types like html, paquet etc check out the [Pandas Documentation](https://pandas.pydata.org/docs/reference/io.html)

### **Connecting to a Database**

1. install a database driver (pip install connection driver)
2. Setup connection
3. Use pandas to write SQL code.

In [27]:
import sqlite3

conn = sqlite3.connect('dummy.db')

pd.read_sql('SELECT * FROM dummy', conn)